In [1]:
from kiteconnect import KiteConnect

# Step 1: Initialize KiteConnect with your API key
api_key = "j6o2ksryh5hoxkxx"
api_secret = "a7580bsq05hpj4dde6wkf9pew6995wsb"
kite = KiteConnect(api_key=api_key)

# Step 2: Get login URL and authenticate manually
print("Login URL:", kite.login_url())

Login URL: https://kite.zerodha.com/connect/login?api_key=j6o2ksryh5hoxkxx&v=3

In [2]:
# Step 3: After login, get the request token from the redirected URL
# Replace this with the actual token you get after login
request_token = "3LjA7yrcCgND2IZiN6RUh2szgOALjjEu"

# Step 4: Generate session and set access token
data = kite.generate_session(request_token=request_token, api_secret=api_secret)
kite.set_access_token(data["access_token"])

# Step 5: Fetch user profile
profile = kite.profile()
print("User Profile:", profile)

# Step 6: Fetch holdings
holdings = kite.holdings()
print("Holdings:", holdings)

User Profile: {'user_id': 'RP1458', 'user_type': 'individual/ind_with_nom', 'email': 'pradeep.jdani@gmail.com', 'user_name': 'Pradeep Kumar', 'user_shortname': 'Pradeep', 'broker': 'ZERODHA', 'exchanges': ['NSE', 'BSE', 'MF'], 'products': ['CNC', 'NRML', 'MIS', 'BO', 'CO'], 'order_types': ['MARKET', 'LIMIT', 'SL', 'SL-M'], 'avatar_url': 'https://s3.ap-south-1.amazonaws.com/zerodha-kite-blobs/avatars/KFVFUF1eZT7Hz2hcqoJjkTvyRmzNQZUd.png', 'meta': {'demat_consent': 'physical'}}

In [6]:
import pandas as pd

df = pd.DataFrame(holdings)

df

,tradingsymbol,exchange,instrument_token,isin,product,price,quantity,used_quantity,t1_quantity,realised_quantity,...,collateral_quantity,collateral_type,discrepancy,average_price,last_price,close_price,pnl,day_change,day_change_percentage,mtf
0,ASIANPAINT,BSE,128209924,INE021A01026,CNC,0,8,0,0,8,...,0,,False,2900.500000,2618.55,2605.00,-2255.600000,13.55,0.520154,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
1,ASTRAL,NSE,3691009,INE006I01046,CNC,0,16,0,0,16,...,0,,False,1489.615625,1557.30,1566.10,1082.950000,-8.80,-0.561905,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
2,ATLANTAELE,NSE,194305793,INE0Z4F01028,CNC,0,20,0,0,20,...,0,,False,766.300000,1081.00,998.05,6294.000000,82.95,8.311207,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
3,BERGEPAINT,BSE,130426884,INE463A01038,CNC,0,11,0,0,11,...,0,,False,572.800000,534.05,544.25,-426.250000,-10.20,-1.874139,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
4,BHARTIARTL,NSE,2714625,INE397D01024,CNC,0,12,0,0,12,...,0,,False,748.250000,2001.50,2094.90,15039.000000,-93.40,-4.458447,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
5,BHARTIHEXA,NSE,6013185,INE343G01021,CNC,0,27,0,0,27,...,0,,False,585.370370,1751.00,1813.90,31472.000010,-62.90,-3.467666,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
6,CDSL,NSE,5420545,INE736A01011,CNC,0,48,0,0,48,...,0,,False,574.121875,1577.80,1532.90,48176.550000,44.90,2.929089,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
7,CELLO,BSE,139267076,INE0LMW01024,CNC,0,18,0,0,18,...,0,,False,819.491666,635.35,644.05,-3314.549988,-8.70,-1.350827,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
8,CRAFTSMAN,BSE,139078660,INE00LO01017,CNC,0,5,0,0,5,...,0,,False,1917.200000,6764.00,6769.05,24234.000000,-5.05,-0.074604,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
9,CRISIL,BSE,128023556,INE007A01025,CNC,0,1,0,0,1,...,0,,False,5361.500000,4730.00,4800.95,-631.500000,-70.95,-1.477833,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
10,HINDUNILVR,BSE,128178180,INE030A01027,CNC,0,9,0,0,9,...,0,,False,2505.183333,2414.50,2436.15,-816.149997,-21.65,-0.888697,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
11,INFY,BSE,128053508,INE009A01021,CNC,0,41,0,0,41,...,0,,False,1456.436585,1477.35,1466.25,857.450015,11.10,0.757033,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
12,INOXINDIA,BSE,139275780,INE616N01034,CNC,0,25,0,0,25,...,0,,False,714.144000,1172.20,1202.90,11451.400000,-30.70,-2.552166,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
13,IRCTC,NSE,3484417,INE335Y01020,CNC,0,30,0,0,30,...,0,,False,678.305000,704.00,703.35,770.850000,0.65,0.092415,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
14,ITC,NSE,424961,INE154A01025,CNC,0,27,0,0,27,...,0,,False,338.248001,404.40,407.50,1786.103973,-3.10,-0.760736,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
15,ITCHOTELS,NSE,7488257,INE379A01028,CNC,0,1,0,0,1,...,0,,False,500.065895,207.91,210.98,-292.155895,-3.07,-1.455114,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
16,JIOFIN,NSE,4644609,INE758E01017,CNC,0,22,0,0,22,...,0,,False,250.594116,299.65,298.10,1079.229448,1.55,0.519960,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
17,JUNIORBEES,BSE,151066628,INF732E01045,CNC,0,23,0,0,23,...,0,,False,729.419130,746.30,745.56,388.260010,0.74,0.099254,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
18,KEI,BSE,132497668,INE878B01027,CNC,0,4,0,0,4,...,0,,False,4387.975000,3950.00,3925.90,-1751.900000,24.10,0.613872,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
19,KIRLPNU,NSE,3886081,INE811A01020,CNC,0,5,0,0,5,...,0,,False,1357.000000,1069.20,1076.40,-1439.000000,-7.20,-0.668896,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
20,LENSKART,BSE,139417604,INE956O01016,CNC,0,37,0,0,37,...,0,,False,402.000000,0.00,0.00,-14874.000000,0.00,0.000000,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
21,MID150BEES,NSE,2177537,INF204KB1V68,CNC,0,28,0,0,28,...,0,,False,222.587857,228.00,226.13,151.540004,1.87,0.826958,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
22,NIFTYBEES,NSE,2707457,INF204KB14I2,CNC,0,42,0,0,42,...,0,,False,282.465000,288.70,288.24,261.870000,0.46,0.159589,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
23,NSDL,BSE,139383556,INE301O01023,CNC,0,9,0,0,9,...,0,,False,1201.600000,1069.60,1057.80,-1188.000000,11.80,1.115523,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
24,PACEDIGITK,NSE,194391553,INE0S3G01027,CNC,0,69,0,0,69,...,0,,False,218.842028,215.40,213.60,-237.499932,1.80,0.842697,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
25,PERSISTENT,NSE,4701441,INE262H01021,CNC,0,11,0,0,11,...,0,,False,2404.665909,5789.00,5842.00,37227.675001,-53.00,-0.907224,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
26,PIDILITIND,BSE,128084740,INE318A01026,CNC,0,40,0,0,40,...,0,,False,1289.456250,1455.75,1441.80,6651.750000,13.95,0.967541,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
27,RELIANCE,BSE,128083204,INE002A01018,CNC,0,18,0,0,18,...,0,,False,1164.754796,1478.25,1495.75,5642.913672,-17.50,-1.169982,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
28,SAATVIKGL,BSE,139398660,INE13B501022,CNC,0,34,0,0,34,...,0,,False,463.255882,490.40,538.15,922.900012,-47.75,-8.872991,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
29,SBIN,BSE,128028676,INE062A01020,CNC,0,34,0,0,34,...,0,,False,562.023529,955.95,960.75,13393.500014,-4.80,-0.499610,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
30,SCHAEFFLER,BSE,129482244,INE513A01022,CNC,0,7,0,0,7,...,0,,False,3166.792857,4106.50,4119.15,6577.950001,-12.65,-0.307102,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
31,SUNDARMFIN,BSE,151058180,INE660A01013,CNC,0,1,0,0,1,...,0,,False,2595.000000,4811.90,4857.90,2216.900000,-46.00,-0.946911,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
32,TATATECH,BSE,139271172,INE142M01025,CNC,0,18,0,0,18,...,0,,False,1072.941666,673.15,677.55,-7196.249988,-4.40,-0.649399,"{'quantity': 0, 'used_quantity': 0, 'average_p..."
33,YATHARTH,BSE,139251204,INE0JO301016,CNC,0,52,0,0,52,...,0,,False,304.496153,784.95,794.95,24983.600044,-10.00,-1.257941,"{'quantity': 0, 'used_quantity': 0, 'average_p..."

In [8]:
df2 = pd.DataFrame( kite.mf_holdings() )
df2

,tradingsymbol,fund,folio,last_price,last_price_date,quantity,pnl,xirr,average_price,discrepancy,pledged_quantity,las_quantity
0,INF204KB15W0,NIPPON INDIA NIFTY SMALLCAP 250 INDEX FUND - D...,488162442993,34.5212,,2239.222,0.0,0.0,33.782,False,0.0,0.0
1,INF247L01AE7,MOTILAL OSWAL NIFTY 50 INDEX FUND - DIRECT PLAN,9105741113,22.3004,,9888.557,0.0,0.0,18.217,False,0.0,0.0
2,INF760K01EL8,CANARA ROBECO ELSS TAX SAVER FUND - DIRECT PLAN,18826480054,202.2400,,683.915,0.0,0.0,127.056,False,0.0,0.0
3,INF277K01I94,TATA ELSS FUND - DIRECT PLAN,3682254/83,235.9847,,194.367,0.0,0.0,92.607,False,0.0,0.0
4,INF740K01OK1,DSP ELSS TAX SAVER FUND - DIRECT PLAN,3865493/65,158.5250,,2890.592,0.0,0.0,104.576,False,0.0,0.0
5,INF109K016L0,ICICI PRUDENTIAL LARGE CAP FUND - DIRECT PLAN,9257327/89,125.2000,,401.489,0.0,0.0,112.699,False,0.0,0.0
6,INF109KB10X0,ICICI PRUDENTIAL BSE SENSEX INDEX FUND - DIREC...,9257327/89,27.8614,,7601.993,0.0,0.0,23.276,False,0.0,0.0
7,INF174V01507,MAHINDRA MANULIFE MID CAP FUND - DIRECT PLAN,1000821161,38.4999,,6922.751,0.0,0.0,32.356,False,0.0,0.0
8,INF179K01UT0,HDFC FLEXI CAP FUND - DIRECT PLAN,36634412/92,2272.0570,,36.569,0.0,0.0,2216.149,False,0.0,0.0
9,INF277K013S8,TATA BALANCED ADVANTAGE FUND - DIRECT PLAN,3682254/83,23.2727,,29508.448,0.0,0.0,20.332,False,0.0,0.0
10,INF209K01P23,ADITYA BIRLA SUN LIFE ELSS TAX SAVER FUND - DI...,1018331805,469.3100,,180.373,0.0,0.0,224.530,False,0.0,0.0
11,INF0R8F01018,ZERODHA NIFTY LARGEMIDCAP 250 INDEX FUND - DIR...,1108245295,14.3589,,15018.193,0.0,0.0,11.865,False,0.0,0.0
12,INF204KB16W8,NIPPON INDIA NIFTY SMALLCAP 250 INDEX FUND - D...,488162442993,34.5212,,388.921,0.0,0.0,25.711,False,0.0,0.0
13,INF0R8F01117,ZERODHA MULTI ASSET PASSIVE FOF - DIRECT PLAN,1108245295,10.8175,,92.672,0.0,0.0,10.790,False,0.0,0.0
14,INF209K01UU3,ADITYA BIRLA SUN LIFE MONEY MANAGER FUND - DIR...,1018331805,383.7522,,1814.621,0.0,0.0,332.939,False,0.0,0.0
15,INF174K01LI3,KOTAK ELSS TAX SAVER FUND - DIRECT PLAN,3984604/80,138.2040,,2868.390,0.0,0.0,90.952,False,0.0,0.0
16,INF761K01DM6,BANK OF INDIA MID u0026 SMALL CAP EQUITY u0026...,9108538554,42.2900,,772.271,0.0,0.0,41.434,False,0.0,0.0
17,INF917K01TK4,HSBC MEDIUM DURATION FUND - DIRECT PLAN,2983116/66,22.8369,,29866.188,0.0,0.0,22.767,False,0.0,0.0
18,INF846K01EW2,AXIS ELSS TAX SAVER FUND - DIRECT PLAN,91058740173,111.7992,,1384.009,0.0,0.0,60.691,False,0.0,0.0
19,INF846K01DP8,AXIS LARGE CAP FUND - DIRECT PLAN,91027809223,71.4900,,853.970,0.0,0.0,50.840,False,0.0,0.0
20,INF277K01I86,TATA ELSS FUND - DIRECT PLAN,3682254/83,52.5399,,7806.994,0.0,0.0,34.647,False,0.0,0.0
21,INF769K01DM9,MIRAE ASSET ELSS TAX SAVER FUND - DIRECT PLAN,78838393543,57.8630,,1896.040,0.0,0.0,34.544,False,0.0,0.0
22,INF209K01WC7,ADITYA BIRLA SUN LIFE CONSUMPTION FUND - DIREC...,1018331805,254.4200,,49.851,0.0,0.0,260.757,False,0.0,0.0
23,INF194K01Y29,BANDHAN ELSS TAX SAVER FUND - DIRECT PLAN,2665612/38,180.3250,,2011.662,0.0,0.0,109.358,False,0.0,0.0